### ISSUE TITLE
NuGet package Microsoft.AspNet.WebHooks.Custom is stuck at v1.2.1 and missing important additions

### ISSUE THREAD

**Issue by stefann42** [aspnet/AspNetWebHooks#13]
NuGet package https://www.nuget.org/packages/Microsoft.AspNet.WebHooks.Custom is stuck at v1.2.1 which doesn't include important additions since like `IWebHookRegistrationsManager` https://github.com/aspnet/AspNetWebHooks/commit/757530d2af40da1d51e0cf387595561e1e5cebf0

**Comment by dougbu** [comment]
Yes, we have not yet shipped 1.3.0 Preview 1.

**Comment by stefann42** [comment]
Is there a release timeline somewhere that perhaps I missed? Thanks!
