### ISSUE TITLE
Webhooks support for AWS SNS messages

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetWebHooks#16]
_From @mteper on Tuesday, November 17, 2015 11:51:10 AM_

See http://blogs.aws.amazon.com/php/post/Tx2G9D94IE6KPAY/Receiving-Amazon-SNS-Messages-in-PHP for example of how to handle (example describes PHP but should be pretty straight-forward).

_Copied from original issue: aspnet/WebHooks#28_

**Comment by dougbu** [comment]
@mteper thanks very much for your issue. This repo is in maintenance mode and we make fixes only for critical issues in this repo.
