### ISSUE TITLE
WebHooks for Office 365

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetWebHooks#17]
_From @rposener on Monday, April 4, 2016 7:37:55 PM_

Saw some of this at build, would be nice if we had a package that would work with the Office 365 WebHooks.  Once the asp.net core port gets a bit further, I will be glad to work on it and submit a pull (for the .net core), but need to figure out an asp.net core port first.

_Copied from original issue: aspnet/WebHooks#51_

**Comment by dougbu** [comment]
@rposener thanks very much for your issue. This repo is in maintenance mode and we make fixes only for critical issues in this repo.
