### ISSUE TITLE
Anyone managed to do this with Gmail?

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetWebHooks#18]
_From @georgiosd on Friday, July 29, 2016 1:43:10 AM_

Documentation to set up gmail webhooks is terrible. 

Anyone managed to do this and can give some guidance?

_Copied from original issue: aspnet/WebHooks#77_

**Comment by aspnet-hello** [comment]
_From @HenrikFrystykNielsen on Friday, July 29, 2016 1:16:35 PM_

It's been a while since I looked at gmail webhooks. Do you have a pointer?

**Comment by aspnet-hello** [comment]
_From @georgiosd on Monday, August 1, 2016 9:08:12 AM_

I have made some progress but still not 100% on the workflow. https://developers.google.com/gmail/api/guides/push

**Comment by dougbu** [comment]
@georgiosd thanks very much for your issue. This repo is in maintenance mode and we make fixes only for critical issues in this repo.
