### ISSUE TITLE
ASP.NET Web Api with enabled versioning + WebHooks

### ISSUE THREAD

**Issue by JakubHolovsky** [aspnet/AspNetWebHooks#32]
I would like to use for our project the Microsoft.AspNet.WebHooks.Receivers.Stripe library. However my WebApi is ApiVersion (Microsoft.AspNet.WebApi.Versioning) enabled. That somehow interferes with the WebHooks default Url which is:

`https://<host>/api/webhooks/incoming/<receiver>`

I am using the sample StripeWebHookHandler from the AspNet samples. I tried putting the ApiVersion on the WebHookHandler like this with no success:

```
[ApiVersion("1")]
[RoutePrefix("api/v{version:apiVersion}/webhooks/incoming/stripe")]
public class StripeWebHookHandler : WebHookHandler
```
I am guessing that this must be a common problem however I haven't found any solution to this, is there anyway:

1) to have the webhook URL versioned using the provided StripeWebHookHandler.

2) to disable the versioning for this particular URL (also tried the [ApiVersionNeutral] attribute).

**Comment by dougbu** [comment]
Hi. It looks like this is a question about how to use ASP.NET WebHooks. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the 'asp.net-webhooks' [tag](https://stackoverflow.com/questions/tagged/asp.net-webhooks).

Please let us know here if you find an answer.

**Comment by dougbu** [comment]
@JakubHolovsky have you resolved your issue? If so, please close this one. If not, please provide more detail.

**Comment by JakubHolovsky** [comment]
@dougbu I resolved the issue by not using your library
