### ISSUE TITLE
Addition of new Storage for the WebHooks

### ISSUE THREAD

**Issue by dgrizwan** [aspnet/AspNetWebHooks#38]
Hi WebHooks,
I am a young professional and recently learned WebHooks and implemented them in some of our projects.
As we use different database storage other than SQL Server so I have built the complete library to handle that storage. That is MongoDB storage. Now I want to help others as well and make that storage a part of this repository for the ASP.NET. How should I proceed? Do I need to get some permission or whatever is the procedure? Kindly let me know.
Again sorry to do this type of comment here but I could not find any other place to contact you. I didn't find any contribution guide. As that page is not found i.e. https://github.com/aspnet/AspNetCore/blob/dev/CONTRIBUTING.md
You can answer me on my email i.e. dgrizwan@gmail.com
Thanks!

**Comment by dgrizwan** [comment]
Is there any update on this, please?

**Comment by dougbu** [comment]
Closing for same reasons as discussed in aspnet/AspLabs#132
